# Generated by Django 5.2.8 on 2025-12-17 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.CreateModel(
            name='HobbyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobby_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('help_text', models.CharField(blank=True, max_length=240)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date & time'), ('select', 'Select'), ('multi_select', 'Multi-select'), ('url', 'URL'), ('list', 'List')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hobby_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.hobbytype')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('sort', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hobby_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='api.hobbytype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=72)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In progress'), ('done', 'Done')], default='backlog', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('hobby_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.hobbytype')),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='api.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddConstraint(
            model_name='hobbytype',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_hobbytype_owner_slug'),
        ),
        migrations.AddConstraint(
            model_name='hobbytype',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_hobbytype_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='fielddefinition',
            constraint=models.UniqueConstraint(fields=('hobby_type', 'key'), name='uniq_fielddef_type_key'),
        ),
        migrations.AddConstraint(
            model_name='savedview',
            constraint=models.UniqueConstraint(fields=('owner', 'hobby_type', 'name'), name='uniq_savedview_owner_type_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_tag_owner_slug'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_tag_owner_name'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['owner', 'hobby_type', 'status'], name='api_entry_owner_i_d1c7d7_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['owner', 'hobby_type', 'updated_at'], name='api_entry_owner_i_8e62ab_idx'),
        ),
    ]
