# Generated by Django 5.2.8 on 2025-12-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_category_remove_item_owner_hobbytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
